# Generated by Django 5.2.1 on 2025-07-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengantar', models.TextField()),
                ('fet1', models.CharField(max_length=75)),
                ('isi_fet1', models.TextField()),
                ('fet2', models.CharField(max_length=75)),
                ('isi_fet2', models.TextField()),
                ('img_fet', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
